CREATE DATABASE IF NOT EXISTS dualex_db;
USE dualex_db;

-- 1. CONFIGURACIÓN (Tabla independiente)
CREATE TABLE CONFIGURACION (
    idConfiguracion TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dias_aviso_caducidad SMALLINT NOT NULL,
    tiempo_finalizacion_convenio SMALLINT NOT NULL
);

-- 2. JERARQUÍA DE USUARIOS
CREATE TABLE USUARIOS (
    idUsuario SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    tipo CHAR(2) NOT NULL DEFAULT 'A' COMMENT 'P=Profesor, A=Alumno'
);

CREATE TABLE PROFESOR (
    idProfesor SMALLINT UNSIGNED PRIMARY KEY,
    CONSTRAINT fk_prof_user FOREIGN KEY (idProfesor) 
        REFERENCES USUARIOS(idUsuario) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COORDINADOR (
    idCoordinador SMALLINT UNSIGNED PRIMARY KEY,
    CONSTRAINT fk_coord_prof FOREIGN KEY (idCoordinador) 
        REFERENCES PROFESOR(idProfesor) ON DELETE CASCADE ON UPDATE CASCADE
);

-- 3. ESTRUCTURA ACADÉMICA
CREATE TABLE CICLOS (
    idCiclo TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    siglas CHAR(5) NOT NULL,
    idCoordinador SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT fk_ciclo_coord FOREIGN KEY (idCoordinador) REFERENCES COORDINADOR(idCoordinador)
);

CREATE TABLE CURSOS (
    idCurso TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    anio_escolar CHAR(5) NOT NULL COMMENT 'Ej: 25-26',
    idCiclo TINYINT UNSIGNED NOT NULL,
    CONSTRAINT fk_curso_ciclo FOREIGN KEY (idCiclo) REFERENCES CICLOS(idCiclo) ON DELETE CASCADE
);

-- 4. EMPRESAS Y CONTACTOS
CREATE TABLE EMPRESAS (
    idEmpresa SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    siglas CHAR(6) NOT NULL,
    inicioConvenio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    url_convenio VARCHAR(100) NOT NULL,
    idCoordinador_Firma SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT fk_emp_coord FOREIGN KEY (idCoordinador_Firma) REFERENCES COORDINADOR(idCoordinador)
);

CREATE TABLE CONTACTO (
    idContacto SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tfnoContacto CHAR(9) NOT NULL,
    nombreContacto VARCHAR(50) NOT NULL,
    titular VARCHAR(50) NOT NULL,
    idEmpresa SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT fk_cont_emp FOREIGN KEY (idEmpresa) REFERENCES EMPRESAS(idEmpresa) ON DELETE CASCADE
);

-- 5. ALUMNOS (Con régimen y empresa opcional)
CREATE TABLE ALUMNOS (
    idAlumno SMALLINT UNSIGNED PRIMARY KEY,
    dni CHAR(15) NOT NULL UNIQUE,
    nuss CHAR(12) NOT NULL UNIQUE,
    nia CHAR(10) NOT NULL UNIQUE,
    telefono CHAR(15) NOT NULL,
    repetidor BIT NOT NULL DEFAULT 0,
    regimen VARCHAR(15) NOT NULL COMMENT 'General o Intensivo',
    idEmpresa SMALLINT UNSIGNED NULL,
    idCurso TINYINT UNSIGNED NOT NULL,
    CONSTRAINT fk_alu_user FOREIGN KEY (idAlumno) REFERENCES USUARIOS(idUsuario) ON DELETE CASCADE,
    CONSTRAINT fk_alu_emp FOREIGN KEY (idEmpresa) REFERENCES EMPRESAS(idEmpresa) ON DELETE SET NULL,
    CONSTRAINT fk_alu_curso FOREIGN KEY (idCurso) REFERENCES CURSOS(idCurso)
);

-- 6. MÓDULOS Y ACTIVIDADES
CREATE TABLE MODULOS (
    idModulo SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    sigla CHAR(10) NOT NULL,
    color CHAR(7) NOT NULL COMMENT 'Hexadecimal: #FFFFFF'
);

CREATE TABLE ACTIVIDADES (
    idActividad SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    idCoordinador SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT fk_act_coord FOREIGN KEY (idCoordinador) REFERENCES COORDINADOR(idCoordinador)
);

-- 7. TAREAS Y ANEXOS
CREATE TABLE TAREAS (
    idTarea SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    descripcion TEXT NOT NULL,
    calificacion TINYINT UNSIGNED NULL,
    comentario TEXT NULL,
    codigo_auto VARCHAR(20) NOT NULL UNIQUE,
    idAlumno SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT fk_tarea_alu FOREIGN KEY (idAlumno) REFERENCES ALUMNOS(idAlumno) ON DELETE CASCADE
);

CREATE TABLE ANEXO_IV (
    idAnexo SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    datos_extra TEXT NULL,
    idAlumno SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT fk_anexo_alu FOREIGN KEY (idAlumno) REFERENCES ALUMNOS(idAlumno) ON DELETE CASCADE
);

-- 8. TABLAS INTERMEDIAS (RELACIONES M:N)

CREATE TABLE CICLO_EMPRESA (
    idCiclo TINYINT UNSIGNED NOT NULL,
    idEmpresa SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idCiclo, idEmpresa),
    CONSTRAINT fk_ce_ciclo FOREIGN KEY (idCiclo) REFERENCES CICLOS(idCiclo) ON DELETE CASCADE,
    CONSTRAINT fk_ce_emp FOREIGN KEY (idEmpresa) REFERENCES EMPRESAS(idEmpresa) ON DELETE CASCADE
);

CREATE TABLE MODULO_PROFESOR (
    idModulo SMALLINT UNSIGNED NOT NULL,
    idProfesor SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idModulo, idProfesor),
    CONSTRAINT fk_mp_mod FOREIGN KEY (idModulo) REFERENCES MODULOS(idModulo),
    CONSTRAINT fk_mp_prof FOREIGN KEY (idProfesor) REFERENCES PROFESOR(idProfesor)
);

CREATE TABLE CURSO_MODULO (
    idCurso TINYINT UNSIGNED NOT NULL,
    idModulo SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idCurso, idModulo),
    CONSTRAINT fk_cm_curso FOREIGN KEY (idCurso) REFERENCES CURSOS(idCurso),
    CONSTRAINT fk_cm_mod FOREIGN KEY (idModulo) REFERENCES MODULOS(idModulo)
);

CREATE TABLE MODULO_ALUMNO_CURSA (
    idAlumno SMALLINT UNSIGNED NOT NULL,
    idModulo SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idAlumno, idModulo),
    CONSTRAINT fk_mac_alu FOREIGN KEY (idAlumno) REFERENCES ALUMNOS(idAlumno),
    CONSTRAINT fk_mac_mod FOREIGN KEY (idModulo) REFERENCES MODULOS(idModulo)
);

CREATE TABLE MODULO_ALUMNO_PENDIENTES (
    idAlumno SMALLINT UNSIGNED NOT NULL,
    idModulo SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idAlumno, idModulo),
    CONSTRAINT fk_map_alu FOREIGN KEY (idAlumno) REFERENCES ALUMNOS(idAlumno),
    CONSTRAINT fk_map_mod FOREIGN KEY (idModulo) REFERENCES MODULOS(idModulo)
);

CREATE TABLE MODULO_ACTIVIDADES (
    idModulo SMALLINT UNSIGNED NOT NULL,
    idActividad SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idModulo, idActividad),
    CONSTRAINT fk_ma_mod FOREIGN KEY (idModulo) REFERENCES MODULOS(idModulo),
    CONSTRAINT fk_ma_act FOREIGN KEY (idActividad) REFERENCES ACTIVIDADES(idActividad)
);

CREATE TABLE TAREA_ACTIVIDAD (
    idTarea SMALLINT UNSIGNED NOT NULL,
    idActividad SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (idTarea, idActividad),
    CONSTRAINT fk_ta_tarea FOREIGN KEY (idTarea) REFERENCES TAREAS(idTarea) ON DELETE CASCADE,
    CONSTRAINT fk_ta_act FOREIGN KEY (idActividad) REFERENCES ACTIVIDADES(idActividad)
);

-- TABLA CRUCIAL: REVISIÓN DE PROFESORES POR MÓDULO
CREATE TABLE MODULO_TAREA_REVISION (
    idModulo SMALLINT UNSIGNED NOT NULL,
    idTarea SMALLINT UNSIGNED NOT NULL,
    revisada BIT NOT NULL DEFAULT 0,
    observaciones TEXT NULL,
    PRIMARY KEY (idModulo, idTarea),
    CONSTRAINT fk_mtr_mod FOREIGN KEY (idModulo) REFERENCES MODULOS(idModulo),
    CONSTRAINT fk_mtr_tarea FOREIGN KEY (idTarea) REFERENCES TAREAS(idTarea) ON DELETE CASCADE
);